### ISSUE TITLE
testing required on ps3

### ISSUE THREAD

**Issue by tynutsu** [wt-student-projects/cell-experiments#11]
i`ve moved all the significant variables for visual tunning in one place in the visual_tunning.h in the common directory

please test the code in ps3 and confirm it is still working, could only test the x86 version

**Comment by tynutsu** [comment]
why can`t I assign any issue to Jonathan? isn't he added in the team here? :)

**Comment by william-taylor** [comment]
I guess I havent added him to the project, or I have an he hasnt accepted haha

**Comment by william-taylor** [comment]
send him a facebook message ;)

**Comment by tynutsu** [comment]
Tested by Jonathan. Code "still" working 👍
