### ISSUE TITLE
Final testing after code cleanup

### ISSUE THREAD

**Issue by tynutsu** [wt-student-projects/cell-experiments#13]
After code cleanup is performed, let's just get the zip unpacked and make sure the code runs accordingly on pc (tinu) on ps3 (william or jonathan)
I marked this as bug only because I like the red colour of the label to mark the issue's importance :D

**Comment by william-taylor** [comment]
Testing on the PS3 worked fine however the output was not great, adjusted the edge tolerance to 2.75 and this fixed the issue
